"""
Agent: YouTube Metadata Generator

Reads the bill report + winning headline + finished podcast script and produces
SEO-friendly YouTube upload metadata: title, description, tags, chapters.
Used to populate the upload form when shipping the per-bill podcast video.
"""
from __future__ import annotations

from pydantic import BaseModel, Field

from .base import AgentBase, SPINE_ENDPOINT


class YouTubeChapter(BaseModel):
    timestamp_seconds: int = Field(description="Seconds into the video, 0-indexed")
    title: str = Field(description="Short chapter title, 3-8 words")


class YouTubeMetadata(BaseModel):
    bill_short: str
    title: str = Field(description="60-100 char YouTube title with hook + bill name")
    description: str = Field(description="500-1500 char description with SEO + provisions cited")
    tags: list[str] = Field(min_length=10, max_length=25, description="Short kw tags, no quotes")
    chapters: list[YouTubeChapter] = Field(min_length=4, max_length=10, description="Chapters with timestamps")
    thumbnail_concept: str = Field(description="One sentence describing what the thumbnail should show")
    short_caption_30s: str = Field(description="A 30-second TikTok/Shorts hook script for cross-posting")


class YouTubeMetadataGenerator(AgentBase):
    name = "youtube_metadata_generator"
    target_endpoint = SPINE_ENDPOINT
    target_model = "spine"
    temperature = 0.4
    max_tokens = 2500
    output_schema = YouTubeMetadata

    def system_prompt(self) -> str:
        return (
            "You generate YouTube upload metadata for a 4-minute legislative-bill explainer podcast. "
            "Title must be hooky but not clickbait, include the headline angle and the bill\'s "
            "common name. Description leads with a 1-paragraph hook, lists 3-5 specific provisions "
            "with USC citations or dollar amounts, and ends with a Bill Analyzer / Anthropic / AMD "
            "credit line. Tags should be search terms a politically engaged user would type. "
            "Chapter timestamps assume a roughly 4-minute (240s) video; first chapter at 0s. "
            "Always output JSON matching the schema."
        )

    def user_prompt(self, chunk_text: str, chunk_id: str,
                    bill_short: str = "(unknown)",
                    headline: str = "(unknown)",
                    video_duration_seconds: int = 240,
                    **context) -> str:
        return f"""Generate YouTube metadata.

Bill short code: {bill_short}
Winning headline: {headline}
Approx video duration: {video_duration_seconds}s

Return JSON:
{{
  "bill_short": "{bill_short}",
  "title": "60-100 char hook + bill name",
  "description": "500-1500 chars: hook paragraph, 3-5 specific provisions with citations, credit line",
  "tags": ["10-25 search terms"],
  "chapters": [
    {{"timestamp_seconds": 0, "title": "Cold open"}},
    {{"timestamp_seconds": 30, "title": "What\'s in the bill"}},
    ...
  ],
  "thumbnail_concept": "One sentence describing what the thumbnail should show",
  "short_caption_30s": "30s TikTok/Shorts script for cross-posting"
}}

Rules:
- Description must end with: "Generated by Bill Analyzer running on AMD Instinct MI300X GPUs. Built for the AMD Developer Hackathon by lablab.ai."
- Tags: lowercase, no #, no quotes (e.g., "immigration policy", "border security 2026")
- Chapters cover the full duration; final chapter starts at least 30s before end.
- Title under 100 characters HARD.

Return ONLY the JSON.

==== BILL ANALYSIS + SCRIPT ====
{chunk_text}
==== END ====
"""
